### ISSUE TITLE
prod checklist

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/or-review-processor#20]
- [ ] deploy scorecard api (develop -> master)
- [ ] manually create relevant scorecards that existed in v3 AND that are used
- [ ] deploy submission api (develop -> master)
